config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  devise_for :admins

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "home#index"
  get "/users/profile" => "home#profile"
  get "/aboutus" => "home#aboutus"
  get "/gallery" => "home#gallery"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get "/mycourse" => "courses#mycourse"

  resource :course_categories
  resources :courses, except: [:destroy], param: :slug do
    resources :enrollments, only: [:new, :create], controller: "course_enrollments"
  end
  resources :certificates, only: [:new, :show] do
    post :validate, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :news, only: [:index, :show], param: :slug
  resources :blogs, param: :slug do
    resources :comments
  end
  resources :assignments, only: [:new, :create]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :news
  has_one_attached :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  has_one_attached :file
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  has_many :comments
  has_one_attached :image
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :certificate_number, presence: true
  validates :user, presence: true
  validates :course, presence: true

  has_one_attached :certificate
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged
  has_rich_text :description

  belongs_to :course_category
  has_one_attached :image
  has_many :course_enrollements
  has_many :users, through: :course_enrollements
  has_many :certificates
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
  has_many :courses
  has_one_attached :image
  enum status: %i[non-active active]
  validates :name, presence: true
end

app/models/course_enrollement.rb
class CourseEnrollement < ApplicationRecord
  belongs_to :user
  belongs_to :course

  enum status: %i[non-active active]
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many_attached :images
end

app/models/news.rb
class News < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  enum status: %i[non-active active]

  belongs_to :admin
  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_one_attached :cnic_front
  has_one_attached :profile
  has_one_attached :cnic_back
  has_one_attached :last_qualification
  has_many :certificates
  has_many :course_enrollements
  has_many :courses, through: :course_enrollements
  has_many :comments
  has_many :assignments

  enum status: %i[non-active active]

  # def active_for_authentication?
  #   if super && active?
  #     true
  #   else
  #     message = "Your account is not active. Please contact the administrator."
  #     redirect_to root_path, alert: message
  #     false
  #   end
  # end

  # def active?
  #   status == 'active'
  # end
  def enrolled_in?(course)
    course_enrollements.where(course_id: course.id).exists?
  end

  after_create :assign_default_role

  def assign_default_role
    add_role(:newuser) if roles.blank?
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find_by!(slug: params[:slug])
    @comments = @blog.comments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @course_categories = CourseCategory.all
    @courses = Course.all
    @news = News.all
    @admins = Admin.all
  end

  def profile
    @assignment = Assignment.new
  end

  def aboutus
    @courses = Course.all
    @admins = Admin.all
  end

  def gallery
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[show]

  def index
    @news = News.all
    @admins = Admin.all
  end

  def show
  end

  private

  def set_news
    @single_news = News.find_by!(slug: params[:slug])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/blogs/index.html.erb
<main>

   <!-- breadcrumb area start -->
   <section class="breadcrumb__area include-bg pt-150 pb-150 breadcrumb__overlay header-img"
      data-background="assets/img/breadcrumb/breadcrumb-bg-1.jpg">
      <div class="container">
         <div class="row">
            <div class="col-xxl-12">
               <div class="breadcrumb__content text-center p-relative z-index-1">
                  <h3 class="breadcrumb__title">Our Blog</h3>
                  <div class="breadcrumb__list">
                     <span>
                        <%= link_to "Home" , root_path%>
                     </span>
                     <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                     <span>Blog</span>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb area end -->

   <!-- blog area start -->
   <section class="blog__area pt-120">
      <div class="container">
         <div class="row">
            <div class="col-xxl-8 col-xl-8 col-lg-8">
               <div class="postbox__wrapper pr-20">
                  <% @blogs.each do |blog| %>
                     <article class="postbox__item format-image mb-50 transition-3">
                        <div class="postbox__thumb w-img">
                           <%= link_to blog_path(blog.slug) do %>
                           <% if blog.image.attached? %>
                              <%= image_tag blog.image %>
                           <% end %>
                           <% end %>
                        </div>
                        <div class="postbox__content">
                           <div class="postbox__meta">
                              <span><i class="far fa-calendar-check"></i>
                                 <%= time_ago_in_words(blog.created_at) %>
                              </span>
                              <span><a href="#"><i class="fal fa-comments"></i>
                                    <%= blog.comments.count %> comments
                                 </a></span>
                           </div>
                           <h3 class="postbox__title">
                              <%= link_to blog.title, blog_path(blog.slug) %>
                           </h3>
                           <div class="postbox__text">
                              <p>
                                 <%= blog.description %>
                              </p>
                           </div>
                           <div class="postbox__read-more">
                              <%= link_to "read more" , blog_path(blog.slug), class: "tp-btn" %>
                           </div>
                        </div>
                     </article>
                     <% end %>

               </div>
            </div>
            <div class="col-xxl-4 col-xl-4 col-lg-4">
               <div class="blog__sidebar pl-70">
                  
                  
                  <div class="sidebar__widget mb-55">
                     <div class="sidebar__widget-head mb-35">
                        <h3 class="sidebar__widget-title">Tags</h3>
                     </div>
                     <div class="sidebar__widget-content">
                        <div class="tagcloud">
                           <a href="#">Art &amp; Design</a>
                           <a href="#">Course</a>
                           <a href="#">Videos</a>
                           <a href="#">App</a>
                           <a href="#">Education</a>
                           <a href="#">Data Science</a>
                           <a href="#">Machine Learning</a>
                           <a href="#">Tips</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- blog area end -->

</main>

app/views/blogs/show.html.erb
<main>

  <!-- breadcrumb area start -->
  <section class="breadcrumb__area include-bg pt-150 pb-150 breadcrumb__overlay header-img data-background="assets/img/breadcrumb/breadcrumb-bg-1.jpg">
     <div class="container">
        <div class="row">
           <div class="col-xxl-12">
              <div class="breadcrumb__content text-center p-relative z-index-1">
                 <h3 class="breadcrumb__title">Our Blog</h3>
                 <div class="breadcrumb__list">
                    <span>Home</span>
                    <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                    <span>Blog</span>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </section>
  <!-- breadcrumb area end -->

  <!-- blog area start -->
  <section class="blog__area pt-120 pb-120">
     <div class="container">
        <div class="row">
           <div class="col-xxl-8 col-xl-8 col-lg-8">
              <div class="postbox__wrapper postbox__details pr-20">
                 <div class="postbox__item transition-3 mb-70">
                    <div class="postbox__thumb m-img">
                     <% if @blog.image.attached? %>
                        <%= image_tag @blog.image %>
                     <% end %>
                    </div>
                    <div class="postbox__content">
                       <div class="postbox__meta">
                          <span><i class="far fa-calendar-check"></i> <%= @blog.created_at%> </span>
                       </div>
                       <h3 class="postbox__title"> <%= @blog.title %></h3>
                       <div class="postbox__text mb-40">
                          <p> <%= @blog.description %></p>
                       </div>
                       <div class="postbox__quote grey-bg-2 mb-45 p-relative fix">
                          <img class="quote" src="assets/img/blog/quote-1.png" alt="">
                          <blockquote>
                             <p>After I started learning design with Quillow, I realized that I had Improved to very advanced levels.</p>
                             <h4>Chris Collins</h4>
                          </blockquote>
                       </div>
                       <div class="postbox__line"></div>
                      
                    </div>
                 </div>
                 <div class="latest-comments mb-65">
                    <h3><%= @comments.count %> Comments</h3>
                    <% @comments.each do |comment| %>
                    <ul>
                       <li>
                          <div class="comments-box grey-bg-2">
                             <div class="comments-info d-flex">
                                   <div class="comments-avatar mr-20">
                                    <% if comment.user.profile.attached? %>
                                       <%= image_tag comment.user.profile %>
                                    <% end %>
                                   </div>
                                   <div class="avatar-name">
                                      <h5> <%= comment.user.firstname %></h5>
                                      <span class="post-meta">  <%= comment.created_at %></span>
                                   </div>
                             </div>
                             <div class="comments-text ml-65">
                                <p> <%= comment.contentofcomment %></p>
                             </div>
                          </div>
                       </li>
                    </ul>
                    <% end %>
                 </div>
                 <div class="postbox__comment">
                    <h3>Write a comment</h3>
                    <%= form_with url: blog_comments_path(@blog), remote: true do |f| %>
  <%= f.fields_for :comment, Comment.new do |comment_form| %>
    <div class="row">
      <div class="col-xxl-12">
        <div class="postbox__comment-input">
          <%= comment_form.text_area :contentofcomment, placeholder: "Enter your comment here", rows: 3 %>
        </div>
      </div>
      <div class="col-xxl-12">
        <div class="postbox__comment-btn">
          <%= comment_form.submit "Submit", class: "btn btn-primary mt-3" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

                 </div>
              </div>
           </div>
           <div class="col-xxl-4 col-xl-4 col-lg-4">
              <div class="blog__sidebar pl-70">
                 
                 <div class="sidebar__widget mb-55">
                    <div class="sidebar__widget-head mb-35">
                       <h3 class="sidebar__widget-title">Category</h3>
                    </div>
                    <div class="sidebar__widget-content">
                          <ul>
                             <li><a href="blog.html">Category</a></li>
                             <li><a href="blog.html">Video & Tips  (4)</a></li>
                             <li><a href="blog.html">Education  (8)</a></li>
                             <li><a href="blog.html">Business  (5)</a></li>
                             <li><a href="blog.html">UX Design  (3)</a></li>
                          </ul>
                    </div>
                 </div>
                 <div class="sidebar__widget mb-55">
                    <div class="sidebar__widget-head mb-35">
                       <h3 class="sidebar__widget-title">Tags</h3>
                    </div>
                    <div class="sidebar__widget-content">
                       <div class="tagcloud">
                          <a href="#">Art & Design</a>
                          <a href="#">Course</a>
                          <a href="#">Videos</a>
                          <a href="#">App</a>
                          <a href="#">Education</a>
                          <a href="#">Data Science</a>
                          <a href="#">Machine Learning</a>
                          <a href="#">Tips</a>
                       </div>
                    </div>
                 </div>
                 <div class="sidebar__widget mb-55">
                    <div class="sidebar__banner w-img">
                       <img src="assets/img/blog/banner/banner-1.jpg" alt="">
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </section>
  <!-- blog area end -->

</main>

app/views/news/index.html.erb
<main>

  <!-- breadcrumb area start -->
  <section class="breadcrumb__area include-bg pt-150 pb-150 breadcrumb__overlay header-img" data-background="assets/img/breadcrumb/breadcrumb-bg-1.jpg">
     <div class="container">
        <div class="row">
           <div class="col-xxl-12">
              <div class="breadcrumb__content text-center p-relative z-index-1">
                 <h3 class="breadcrumb__title">News</h3>
                 <div class="breadcrumb__list">
                  <span><%= link_to "Home", root_path%></span>
                    <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                    <span>News</span>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </section>
  <!-- breadcrumb area end -->

  <!-- event area start -->
  <section class="event__area pt-115">
     <div class="container">
        <div class="row">
           <div class="col-xxl-12">
              <div class="section__title-wrapper-2 text-center mb-60">
                 <span class="section__title-pre-2">Featured News</span>
                 <h3 class="section__title-2">Follow our latest news</h3>
              </div>
           </div>
        </div>
        <div class="row">
          <% @news.each do |news| %>
          <div class="col-xxl-12">
             <div
                class="event__item white-bg mb-10 transition-3 p-relative d-lg-flex align-items-center justify-content-between" data-aos="fade-up">
                <div class="event__left d-sm-flex align-items-center">
                   <div class="event__date">
                      <h4><%= news.date.day %></h4>
                      <p><%= news.date.strftime("%B, %Y") %></p>
                    </div>
                    
                   <div class="event__content">
                      <div class="event__meta">
                         <ul>
                            <li>
                               <a href="#"><svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                     <path
                                        d="M8.49992 9.51253C9.72047 9.51253 10.7099 8.52308 10.7099 7.30253C10.7099 6.08198 9.72047 5.09253 8.49992 5.09253C7.27937 5.09253 6.28992 6.08198 6.28992 7.30253C6.28992 8.52308 7.27937 9.51253 8.49992 9.51253Z"
                                        stroke="#5F6160" stroke-width="1.5" />
                                     <path
                                        d="M2.56416 6.01334C3.95958 -0.120822 13.0475 -0.113738 14.4358 6.02043C15.2504 9.61876 13.0121 12.6646 11.05 14.5488C9.62625 15.9229 7.37375 15.9229 5.94291 14.5488C3.98791 12.6646 1.74958 9.61168 2.56416 6.01334Z"
                                        stroke="#5F6160" stroke-width="1.5" />
                                  </svg>
                                  <%= news.location %></a>
                            </li>
                         </ul>
                      </div>
                      <h3 class="event__title">
                         <%= link_to news.title, news_path(news.slug) %>
                      </h3>

                      <div class="event__person">
                         <ul>
                            <li>
                               <a href="#">
                                 <% if news.admin.profile.attached? %>
                                       <%= image_tag news.admin.profile %>
                                    <% end %>
                                  <span><%= news.admin.first_name %> <%= news.admin.last_name %></span>
                                </a>
                            </li>
                         </ul>
                      </div>
                   </div>
                </div>
          </div>
       </div>
       <% end %>
    </div>
     </div>
  </section>
  <!-- event area end -->

  <!-- team area start -->
  <!-- team area end -->


</main>

app/views/news/show.html.erb
<main>

  <!-- event area start -->
  <section class="event__area pt-115 p-relative">
    <div class="page__title-shape">
      <img class="page-title-shape-5 d-none d-sm-block" src="assets/img/breadcrumb/page-title-shape-1.png" alt="">
      <img class="page-title-shape-6" src="assets/img/breadcrumb/page-title-shape-2.png" alt="">
      <img class="page-title-shape-7" src="assets/img/breadcrumb/page-title-shape-4.png" alt="">
      <img class="page-title-shape-8" src="assets/img/breadcrumb/page-title-shape-5.png" alt="">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xxl-8">
          <div class="event__wrapper">
            <div class="page__title-content mb-25">
              <div class="breadcrumb__list breadcrumb__list-2 mb-10">
                <span><%= link_to "Home", root_path%></span>
                <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                <span>News</span>
              </div>
              <h5 class="breadcrumb__title-2"><%= @single_news.title %></h5>
            </div>
            <div class="course__meta-2 d-sm-flex align-items-center mb-30">
              <div class="course__teacher-3 d-flex align-items-center mr-70 mb-30">
                <div class="course__teacher-thumb-3 mr-15">
                  <% if @single_news.admin.profile.attached? %>
                    <%= image_tag @single_news.admin.profile %>
                  <% end %>
                </div>
                <div class="course__teacher-info-3">
                  <h5>Teacher</h5>
                  <p><%= @single_news.admin.first_name %> <%= @single_news.admin.last_name %></p>
                </div>
              </div>
              <div class="course__update mr-80 mb-30">
                <h5>Last Update:</h5>
                <p><%= @single_news.updated_at.strftime("%B, %Y") %></p>
              </div>
              <div class="course__rating-2 mb-30">
                <h5>Review:</h5>
                <div class="course__rating-inner d-flex align-items-center">
                  <ul>
                    <li><a href="#"><i class="fa-solid fa-star"></i></a></li>
                    <li><a href="#"><i class="fa-solid fa-star"></i></a></li>
                    <li><a href="#"><i class="fa-solid fa-star"></i></a></li>
                    <li><a href="#"><i class="fa-solid fa-star"></i></a></li>
                    <li><a href="#"><i class="fa-solid fa-star"></i></a></li>
                  </ul>
                  <p>4.5</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- event area end -->

  <!-- event details area start -->
  <section class="event__area pb-110">
    <div class="container">
      <div class="row">
        <div class="col-xxl-8 col-xl-8 col-lg-8">
          <div class="event_wrapper">
            <div class="event__thumb mb-35 w-img">
              <% if @single_news.admin.profile.attached? %>
              <%= image_tag @single_news.admin.profile %>
            <% end %>
                      </div>
            <div class="event__details mb-35">
              <h3>Description</h3>
              <p><%= @single_news.description %></p>
            </div>
            <div class="event__tag">
              <span><i class="fal fa-tag"></i></span>
              <a href="#"><%= @single_news.tags %>, </a>
            </div>
          </div>
        </div>
        <div class="col-xxl-4 col-xl-4 col-lg-4">
          <div class="event__sidebar pl-70">
            <div class="event__sidebar-widget white-bg mb-20">
              <div class="event__sidebar-shape">
                <img class="event-sidebar-img-2" src="assets/img/events/event-shape-2.png" alt="">
                <img class="event-sidebar-img-3" src="assets/img/events/event-shape-3.png" alt="">
              </div>
              <div class="event__info">
                <div class="event__info-content mb-35">
                  <ul>
                    
                    <li class="d-flex align-items-center">
                      <div class="event__info-icon">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                          x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;"
                          xml:space="preserve">
                          <path class="st0"
                            d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z" />
                          <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 " />
                        </svg>
                      </div>
                      <div class="event__info-item">
                        <h5><span>Venue: </span><%= @single_news.location %></h5>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="event__sidebar-widget white-bg">
              <div class="event__sponsor">
                <h3 class="event__sponsor-title">Sponsors</h3>
                <div class="event__sponsor-thumb mb-35">
                  <img src="assets/img/events/sponsor-logo.png" alt="">
                </div>
                <div class="event__sponsor-info">
                  <h3>Thomas R. Toe</h3>
                  <h4>Email: <span>support@educal.com</span></h4>
                  <div class="event__social d-xl-flex align-items-center">
                    <h4>Share:</h4>
                    <ul>
                      <li><a href="#" class="fb"><i class="fa-brands fa-facebook-f"></i></a></li>
                      <li><a href="#" class="tw"><i class="fa-brands fa-twitter"></i></a></li>
                      <li><a href="#" class="pin"><i class="fa-brands fa-pinterest-p"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- event details area end -->


</main>