config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  devise_for :admins

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "home#index"
  get "/users/profile" => "home#profile"
  get "/aboutus" => "home#aboutus"
  get "/gallery" => "home#gallery"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get "/mycourse" => "courses#mycourse"

  resource :course_categories
  resources :courses, except: [:destroy], param: :slug do
    resources :enrollments, only: [:new, :create], controller: "course_enrollments"
  end
  resources :certificates, only: [:new, :show] do
    post :validate, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :news, only: [:index, :show], param: :slug
  resources :blogs, param: :slug do
    resources :comments
  end
  resources :assignments, only: [:new, :create]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :news
  has_one_attached :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  has_one_attached :file
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  has_many :comments
  has_one_attached :image
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :certificate_number, presence: true
  validates :user, presence: true
  validates :course, presence: true

  has_one_attached :certificate
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged
  has_rich_text :description

  belongs_to :course_category
  has_one_attached :image
  has_many :course_enrollements
  has_many :users, through: :course_enrollements
  has_many :certificates
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
  has_many :courses
  has_one_attached :image
  enum status: %i[non-active active]
  validates :name, presence: true
end

app/models/course_enrollement.rb
class CourseEnrollement < ApplicationRecord
  belongs_to :user
  belongs_to :course

  enum status: %i[non-active active]
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many_attached :images
end

app/models/news.rb
class News < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  enum status: %i[non-active active]

  belongs_to :admin
  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_one_attached :cnic_front
  has_one_attached :profile
  has_one_attached :cnic_back
  has_one_attached :last_qualification
  has_many :certificates
  has_many :course_enrollements
  has_many :courses, through: :course_enrollements
  has_many :comments
  has_many :assignments

  enum status: %i[non-active active]

  # def active_for_authentication?
  #   if super && active?
  #     true
  #   else
  #     message = "Your account is not active. Please contact the administrator."
  #     redirect_to root_path, alert: message
  #     false
  #   end
  # end

  # def active?
  #   status == 'active'
  # end
  def enrolled_in?(course)
    course_enrollements.where(course_id: course.id).exists?
  end

  after_create :assign_default_role

  def assign_default_role
    add_role(:newuser) if roles.blank?
  end
end

app/controllers/course_enrollments_controller.rb
# app/controllers/course_enrollments_controller.rb
class CourseEnrollmentsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_course

  def new
    @enrollment = @course.course_enrollements.build
  end

  def create
    @enrollment = @course.course_enrollements.build(enrollment_params)
    @enrollment.user = current_user

    if @enrollment.save
      flash[:success] = "Course is enrolled"
      redirect_to @course
    else
      flash[:alert] = "There was an error enrolling the course."
      render :new
    end
  end

  private

  def set_course
    @course = Course.find_by!(slug: params[:course_slug])
  end

  def enrollment_params
    params.require(:course_enrollement).permit(:course_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @course_categories = CourseCategory.all
    @courses = Course.all
    @news = News.all
    @admins = Admin.all
  end

  def profile
    @assignment = Assignment.new
  end

  def aboutus
    @courses = Course.all
    @admins = Admin.all
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/course_enrollments_helper.rb
module CourseEnrollmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/course_enrollments/new.html.erb
<main>

  <section class="event__area pt-115 p-relative">
    <div class="page__title-shape">
      <img class="page-title-shape-5 d-none d-sm-block" src="assets/img/breadcrumb/page-title-shape-1.png" alt="">
      <img class="page-title-shape-6" src="assets/img/breadcrumb/page-title-shape-2.png" alt="">
      <img class="page-title-shape-7" src="assets/img/breadcrumb/page-title-shape-4.png" alt="">
      <img class="page-title-shape-8" src="assets/img/breadcrumb/page-title-shape-5.png" alt="">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xxl-8">
          <div class="event__wrapper">
            <div class="page__title-content mb-25">
              <div class="breadcrumb__list breadcrumb__list-2 mb-10">
                <span>
                  <%= link_to "Home" , root_path%>
                </span>
                <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                <span>Courses</span>
              </div>
              <span class="breadcrumb__title-pre">
                <%= @course.course_category.name%>
              </span>
              <h5 class="breadcrumb__title-2">
                <%= @course.title%>
              </h5>
            </div>
          </div>
        </div>
      </div>
      
              <div class="row">
              </div>
              <div class="row">
                <div class="col-xxl-6 offset-xxl-3 col-xl-6 offset-xl-3 col-lg-8 offset-lg-2">
                  <div class="sign__wrapper white-bg">

                    <div class="sign__form justify-content-center">
                      <%= form_with model: @enrollment, url: course_enrollments_path(course_slug: @course.slug), method: :post do |f| %>
                      <% if @enrollment.errors.any? %>
                        <div class="alert alert-danger">
                          <% @enrollment.errors.each do |error| %>
                            <%= error %>
                              <% end %>
                        </div>
                        <% end %>
                        <div class="sign__input-wrapper mb-25">
                          <%= f.label :course_title%>
                            <div class="sign__input">
                              <%= f.hidden_field :course_id, value: @course.id %>
                              <%= f.text_field :course_title, value: @course.title, readonly: true %>
                              <i class="fal fa-envelope"></i>
                            </div>
                        </div>
                        <div class="text-center">
                          <%= f.submit "Enroll" , class: "btn btn-primary btn-lg" %>
                        </div>
                          <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
    </div>

  </section>
  <!-- event area end -->

  <!-- event details area start -->

  <!-- event details area end -->

<br>
</main>