config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  devise_for :admins

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "home#index"
  get "/users/profile" => "home#profile"
  get "/aboutus" => "home#aboutus"
  get "/gallery" => "home#gallery"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get "/mycourse" => "courses#mycourse"

  resource :course_categories
  resources :courses, except: [:destroy], param: :slug do
    resources :enrollments, only: [:new, :create], controller: "course_enrollments"
  end
  resources :certificates, only: [:new, :show] do
    post :validate, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :news, only: [:index, :show], param: :slug
  resources :blogs, param: :slug do
    resources :comments
  end
  resources :assignments, only: [:new, :create]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :news
  has_one_attached :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  has_one_attached :file
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  has_many :comments
  has_one_attached :image
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :certificate_number, presence: true
  validates :user, presence: true
  validates :course, presence: true

  has_one_attached :certificate
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged
  has_rich_text :description

  belongs_to :course_category
  has_one_attached :image
  has_many :course_enrollements
  has_many :users, through: :course_enrollements
  has_many :certificates
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
  has_many :courses
  has_one_attached :image
  enum status: %i[non-active active]
  validates :name, presence: true
end

app/models/course_enrollement.rb
class CourseEnrollement < ApplicationRecord
  belongs_to :user
  belongs_to :course

  enum status: %i[non-active active]
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many_attached :images
end

app/models/news.rb
class News < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  enum status: %i[non-active active]

  belongs_to :admin
  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_one_attached :cnic_front
  has_one_attached :profile
  has_one_attached :cnic_back
  has_one_attached :last_qualification
  has_many :certificates
  has_many :course_enrollements
  has_many :courses, through: :course_enrollements
  has_many :comments
  has_many :assignments

  enum status: %i[non-active active]

  # def active_for_authentication?
  #   if super && active?
  #     true
  #   else
  #     message = "Your account is not active. Please contact the administrator."
  #     redirect_to root_path, alert: message
  #     false
  #   end
  # end

  # def active?
  #   status == 'active'
  # end
  def enrolled_in?(course)
    course_enrollements.where(course_id: course.id).exists?
  end

  after_create :assign_default_role

  def assign_default_role
    add_role(:newuser) if roles.blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @course_categories = CourseCategory.all
    @courses = Course.all
    @news = News.all
    @admins = Admin.all
  end

  def profile
    @assignment = Assignment.new
  end

  def aboutus
    @courses = Course.all
    @admins = Admin.all
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_footer.html.erb
<footer>
   <div class="footer__area">
      <div class="footer__top grey-bg-4 pt-95 pb-45">
         <div class="container">
            <div class="row">
               <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-7">
                  <div class="footer__widget footer__widget-2 footer-col-2-1 mb-50">
                     <div class="footer__logo">
                        <div class="logo">
                           <img src="images/logo/logo.webp" alt="logo", width: "150" , height: "100%">
                        </div>
                     </div>
                     <div class="footer__widget-content">
                        <div class="footer__widget-info">
                           <p>We believe everyone should have the opportunity to create progress through technology.</p>
                           <div class="footer__social">
                              <h4>Follow Us</h4>
                              <ul>
                                 <li><a href="https://www.facebook.com/profile.php?id=100091312520201"><i class="fa-brands fa-facebook-f"></i></a></li>
                                 <li><a href="https://twitter.com/Abid_hx?t=2RkVmQyaRr8sJeDq4keoLw&s=09"><i class="fa-brands fa-twitter"></i></a></li>
                                 <li><a href="https://www.linkedin.com/in/betatechpk/"><i class="fa-brands fa-linkedin-in"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-3 col-sm-5">
                  <div class="footer__widget footer__widget-2 mb-50 footer-col-2-2">
                     <h3 class="footer__widget-title">Explore</h3>
                     <div class="footer__widget-content">
                        <ul>
                           <li>
                              <%= link_to "About" , aboutus_path %>
                           </li>
                           <li>
                              <%= link_to "Courses" , courses_path %>
                           </li>
                           <li>
                              <%= link_to "News" , news_index_path %>
                           </li>
                           <li>
                              <%= link_to "Contact" , new_contact_path %>
                           </li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-3 col-sm-5">
                  <div class="footer__widget footer__widget-2 mb-50 footer-col-2-3">
                     <h3 class="footer__widget-title">Links</h3>
                     <div class="footer__widget-content">
                        <ul>
                           <li>
                              <%= link_to "Blogs" , blogs_path %>
                           </li>
                           <li>
                              <a href="#">Gallery</a>
                           </li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 col-sm-7">
                  <div class="footer__widget footer__widget-2 footer-col-2-4 mb-50">
                     <h3 class="footer__widget-title">Sign up for our newsletter</h3>
                     <div class="footer__subscribe">
                        <p>Receive weekly newsletter with educational materials, popular books and much more!</p>
                        <form action="#">
                           <div class="footer__subscribe-input">
                              <input type="text" placeholder="Email">
                              <button type="submit" class="tp-btn-subscribe">Subscribe</button>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="footer__bottom grey-bg-4">
         <div class="container">
            <div class="footer__bottom-inner">
               <div class="row">
                  <div class="col-xxl-12">
                     <div class="footer__copyright text-center">
                        <p>© 2023 Beta Tech. All Rights Reserved</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</footer>

app/views/shared/_header.html.erb
<header>
   <div id="header-sticky" class="header__area header__transparent header__sticky">
      <div class="header__bottom">
         <div class="container">
            <div class="row align-items-center">
               <div class="col-xxl-8 col-xl-9 col-lg-10 col-md-6 col-6">
                  <div class="header__bottom-left d-flex align-items-center">
                     <div class="logo">
                        <%= link_to(root_path) do %>
                           <%= image_tag("logo/logo.png", alt: "logo" , width: "150" , height: "100%" ) %>
                        <% end %>
                     </div>
                     <div class="main-menu main-menu-2 main-menu-border ml-30 pl-30">
                        <nav id="mobile-menu">
                           <ul>
                              <li>
                                 <%= link_to "Home" , root_path %>
                              </li>
                              <li>
                                 <%= link_to "About" , aboutus_path %>
                              </li>
                              <li>
                                 <%= link_to "Courses" , courses_path %>
                              </li>
                              <li class="has-dropdown">
                                 <a>Pages</a>
                                 <ul class="submenu">
                                    <li><a><%= link_to "Certificate Validation" , new_certificate_path %></a></li>
                                       <% if user_signed_in? %>
                                       <li>
                                          <a >
                                          <%= link_to "Profile" , users_profile_path %>
                                       </a>
                                       </li>
                                       <% end %>
                                 </ul>
                              </li>
                              <li>
                                 <%= link_to "Blog" , blogs_path %>
                              </li>
                              <li>
                                 <%= link_to "Contact" , new_contact_path %>
                              </li>
                           </ul>
                        </nav>
                     </div>
                  </div>
               </div>
               <div class="col-xxl-4 col-xl-3 col-lg-2 col-md-6 col-6">
                  <div class="header__bottom-right d-flex justify-content-end align-items-center">
                     <div class="header__action d-none d-xl-block">
                        <ul>
                           <li>
                              <% if user_signed_in? %>
                                 <%= link_to users_profile_path do %>
                                    <% if current_user.profile.attached? %>
                                    <%= image_tag current_user.profile, class: 'profile__basic-thumb mr-30', width: 40, height: 40 %>
                                 <% end %>
                                       <% end %>
                                          <% else %>
                                             <%= link_to user_session_path do %>
                                                <%= raw('<svg width="15" height="20" viewBox="0 0 15 20" fill="none"
                                                   xmlns="http://www.w3.org/2000/svg">
                                                   <path
                                                      d="M7.1466 8.96416C7.05493 8.95499 6.94493 8.95499 6.8441 8.96416C4.66243 8.89083 2.92993 7.10333 2.92993 4.90333C2.92993 2.65749 4.74493 0.833328 6.99993 0.833328C9.24576 0.833328 11.0699 2.65749 11.0699 4.90333C11.0608 7.10333 9.32826 8.89083 7.1466 8.96416Z"
                                                      stroke="#0C140F" stroke-width="1.5" stroke-linecap="round"
                                                      stroke-linejoin="round" />
                                                   <path
                                                      d="M2.56341 12.3467C0.345075 13.8317 0.345075 16.2517 2.56341 17.7275C5.08424 19.4142 9.21841 19.4142 11.7392 17.7275C13.9576 16.2425 13.9576 13.8225 11.7392 12.3467C9.22758 10.6692 5.09341 10.6692 2.56341 12.3467Z"
                                                      stroke="#0C140F" stroke-width="1.5" stroke-linecap="round"
                                                      stroke-linejoin="round" />
                                                   </svg>') %>
                                                   <% end %>
                                                      <% end %>
                           </li>
                        </ul>
                     </div>
                     <div class="header__hamburger d-xl-none">
                        <button type="button" data-bs-toggle="modal" data-bs-target="#offcanvasmodal"
                           class="hamurger-btn">
                           <span></span>
                           <span></span>
                           <span></span>
                        </button>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</header>
<!-- header area end -->


<div class="modal fade" id="offcanvasmodal" tabindex="-1" aria-labelledby="offcanvasmodal" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="offcanvas__wrapper">
            <div class="offcanvas__content">
               <div class="offcanvas__top mb-40 d-flex justify-content-between align-items-center">
                  <div class="offcanvas__logo logo">
                     <%= link_to(image_tag("logo/logo.png", alt: "logo" ), root_path) %>
                  </div>
                  <div class="offcanvas__close">
                     <button class="offcanvas__close-btn" data-bs-toggle="modal" data-bs-target="#offcanvasmodal">
                        <i class="fal fa-times"></i>
                     </button>
                  </div>
               </div>
               <div class="mobile-menu fix"></div>
               <div class="offcanvas__text d-none d-lg-block">
                  <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was
                     born and will give you a complete account of the system and expound the actual teachings of the
                     great explore</p>
               </div>
               <div class="offcanvas__map d-none d-lg-block mb-15">
                  <iframe
                     src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d29176.030811137334!2d90.3883827!3d23.924917699999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1605272373598!5m2!1sen!2sbd"></iframe>
               </div>
               <nav >
                  <ul class="mob-nav" style="list-style: none; text-transform: uppercase; font-weight: bolder;">
                     <li>
                        <%= link_to "Home" , root_path %>
                     </li>
                     <li>
                        <%= link_to "About" , aboutus_path %>
                     </li>
                     <li>
                        <%= link_to "Courses" , courses_path %>
                     </li>
                     <li class="has-dropdown">
                        <a>Pages</a>
                        <ul class="submenu" style="list-style: none;">
                           <li>
                              <%= link_to "Certificate Validation" , new_certificate_path %>
                           </li>
                           <% if user_signed_in? %>
                              <li>
                                 <%= link_to "Profile" , users_profile_path %>
                              </li>
                              <% end %>
                        </ul>
                     </li>
                     <li>
                        <%= link_to "Blog" , blogs_path %>
                     </li>
                     <li>
                        <%= link_to "Contact" , new_contact_path %>
                     </li>
                        <li>
                           <% if user_signed_in? %>
                              <%= link_to destroy_user_session_path, method: :delete do %>
                              
                                    Logout
                                    <% end %>
                                       <% else %>
                                          <%= link_to user_session_path do %>
                                                Login
                                                <% end %>
                                                   <% end %>
                        </li>
                  </ul>
               </nav>
               <div class="offcanvas__contact mt-30 mb-20">
                  <h4>Contact Info</h4>
                  <ul>
                     <li class="d-flex align-items-center">
                        <div class="offcanvas__contact-icon mr-15">
                           <i class="fal fa-map-marker-alt"></i>
                        </div>
                        <div class="offcanvas__contact-text">
                           <a target="_blank"
                              href="https://www.google.com/maps/place/Dhaka/@23.7806207,90.3492859,12z/data=!3m1!4b1!4m5!3m4!1s0x3755b8b087026b81:0x8fa563bbdd5904c2!8m2!3d23.8104753!4d90.4119873">12/A,
                              Mirnada City Tower, NYC</a>
                        </div>
                     </li>
                     <li class="d-flex align-items-center">
                        <div class="offcanvas__contact-icon mr-15">
                           <i class="fas fa-phone"></i>
                        </div>
                        <div class="offcanvas__contact-text">
                           <a href="mailto:support@gmail.com">088889797697</a>
                        </div>
                     </li>
                     <li class="d-flex align-items-center">
                        <div class="offcanvas__contact-icon mr-15">
                           <i class="fal fa-envelope"></i>
                        </div>
                        <div class="offcanvas__contact-text">
                           <a href="tel:+012-345-6789">support@mail.com</a>
                        </div>
                     </li>
                  </ul>
               </div>
               <div class="offcanvas__social">
                  <ul>
                     <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
                     <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
                     <li><a href="#"><i class="fa-brands fa-linkedin-in"></i></a></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
<!-- offcanvas area end -->
<div class="body-overlay"></div>

app/views/shared/_toastr.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <%= javascript_tag "toastr.#{type}('#{message}')" %>
<% end %>