config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
  devise_for :admins

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "home#index"
  get "/users/profile" => "home#profile"
  get "/aboutus" => "home#aboutus"
  get "/gallery" => "home#gallery"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get "/mycourse" => "courses#mycourse"

  resource :course_categories
  resources :courses, except: [:destroy], param: :slug do
    resources :enrollments, only: [:new, :create], controller: "course_enrollments"
  end
  resources :certificates, only: [:new, :show] do
    post :validate, on: :collection
  end
  resources :contacts, only: [:new, :create]
  resources :news, only: [:index, :show], param: :slug
  resources :blogs, param: :slug do
    resources :comments
  end
  resources :assignments, only: [:new, :create]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :news
  has_one_attached :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  has_one_attached :file
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  has_many :comments
  has_one_attached :image
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :certificate_number, presence: true
  validates :user, presence: true
  validates :course, presence: true

  has_one_attached :certificate
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged
  has_rich_text :description

  belongs_to :course_category
  has_one_attached :image
  has_many :course_enrollements
  has_many :users, through: :course_enrollements
  has_many :certificates
  enum status: %i[non-active active]

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
  has_many :courses
  has_one_attached :image
  enum status: %i[non-active active]
  validates :name, presence: true
end

app/models/course_enrollement.rb
class CourseEnrollement < ApplicationRecord
  belongs_to :user
  belongs_to :course

  enum status: %i[non-active active]
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many_attached :images
end

app/models/news.rb
class News < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  enum status: %i[non-active active]

  belongs_to :admin
  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :slug, presence: true
  validates :status, presence: true
  validates :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_one_attached :cnic_front
  has_one_attached :profile
  has_one_attached :cnic_back
  has_one_attached :last_qualification
  has_many :certificates
  has_many :course_enrollements
  has_many :courses, through: :course_enrollements
  has_many :comments
  has_many :assignments

  enum status: %i[non-active active]

  # def active_for_authentication?
  #   if super && active?
  #     true
  #   else
  #     message = "Your account is not active. Please contact the administrator."
  #     redirect_to root_path, alert: message
  #     false
  #   end
  # end

  # def active?
  #   status == 'active'
  # end
  def enrolled_in?(course)
    course_enrollements.where(course_id: course.id).exists?
  end

  after_create :assign_default_role

  def assign_default_role
    add_role(:newuser) if roles.blank?
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show]
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def show
  end

  def mycourse
    @enrollments = CourseEnrollement.where(user_id: current_user.id)
    @mycourse = @enrollments.map(&:course)
  end

  private

  def set_course
    @course = Course.find_by!(slug: params[:slug])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @course_categories = CourseCategory.all
    @courses = Course.all
    @news = News.all
    @admins = Admin.all
  end

  def profile
    @assignment = Assignment.new
  end

  def aboutus
    @courses = Course.all
    @admins = Admin.all
  end

  def gallery
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[show]

  def index
    @news = News.all
    @admins = Admin.all
  end

  def show
  end

  private

  def set_news
    @single_news = News.find_by!(slug: params[:slug])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/courses/index.html.erb
<main>

   <!-- breadcrumb area start -->
   <section class="breadcrumb__area include-bg pt-150 pb-150 breadcrumb__overlay header-img"
      data-background="assets/img/breadcrumb/breadcrumb-bg-1.jpg">
      <div class="container">
         <div class="row">
            <div class="col-xxl-12">
               <div class="breadcrumb__content text-center p-relative z-index-1">
                  <h3 class="breadcrumb__title">Our Courses</h3>
                  <div class="breadcrumb__list">
                     <span>
                        <%= link_to "Home" , root_path%>
                     </span>
                     <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                     <span>Courses</span>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb area end -->


   <!-- course area start -->
   <section class="course__area pt-115 pb-90 grey-bg-3">
      <div class="container">
         <div class="row">
            <div class="col-xxl-12">
               <div class="course__tab-conent">
                  <div class="tab-content" id="courseTabContent">
                     <div class="tab-pane fade show active" id="grid" role="tabpanel" aria-labelledby="grid-tab">
                        <div class="row">
                           <% @courses.each do |course|%>
                              <div class="col-xxl-4 col-xl-4 col-lg-6 col-md-6">
                                 <div class="course__item white-bg transition-3 mb-30">
                                    <div class="course__thumb w-img fix">
                                       <%= link_to course_path(course.slug) do %>
                                       <% if course.image.attached? %>
                                          <%= image_tag course.image %>
                                       <% end %>
                                       <% end %>
                                    </div>
                                    <div class="course__content p-relative">
                                       <div class="course__price">
                                          <span>PKR<%= course.price %></span>
                                       </div>
                                       <div class="course__tag">
                                          <a href="#">
                                             <%= course.course_category.name %>
                                          </a>
                                       </div>
                                       <h3 class="course__title">
                                          <%= link_to course.title, course_path(course.slug) %>
                                       </h3>
                                       <!-- <% if course.description.to_plain_text.length> 250 %>
                                          
                                          <% else %>
                                             <p>
                                                <%= course.description %>
                                             </p>
                                             <% end %> -->
                                    </div>
                                 </div>
                              </div>
                              <% end %>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>

      </div>
   </section>
   <!-- course area end -->


</main>

app/views/courses/mycourse.html.erb
<main>

   <!-- breadcrumb area start -->
   <section class="breadcrumb__area include-bg pt-150 pb-150 breadcrumb__overlay header-img"
      data-background="assets/img/breadcrumb/breadcrumb-bg-1.jpg">
      <div class="container">
         <div class="row">
            <div class="col-xxl-12">
               <div class="breadcrumb__content text-center p-relative z-index-1">
                  <h3 class="breadcrumb__title">MY Courses</h3>
                  <div class="breadcrumb__list">
                     <span>
                        <%= link_to "Home" , root_path%>
                     </span>
                     <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                     <span>Courses</span>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb area end -->


   <!-- course area start -->
   <section class="course__area pt-115 pb-90 grey-bg-3">
      <div class="container">
         <div class="row">
            <div class="col-xxl-12">
               <div class="course__tab-conent">
                  <div class="tab-content" id="courseTabContent">
                     <div class="tab-pane fade show active" id="grid" role="tabpanel" aria-labelledby="grid-tab">
                        <div class="row">
                           <% @mycourse.each do |course|%>
                              <div class="col-xxl-4 col-xl-4 col-lg-6 col-md-6">
                                 <div class="course__item white-bg transition-3 mb-30">
                                    <div class="course__thumb w-img fix">
                                       <%= link_to course_path(course.slug) do %>
                                       <% if course.image.attached? %>
                                          <%= image_tag course.image %>
                                       <% end %>
                                       <% end %>
                                    </div>
                                    <div class="course__content p-relative">
                                       <div class="course__price">
                                          <span>PKR<%= course.price %></span>
                                       </div>
                                       <div class="course__tag">
                                          <a href="#">
                                             <%= course.course_category.name %>
                                          </a>
                                       </div>
                                       <h3 class="course__title">
                                          <%= link_to course.title, course_path(course.slug) %>
                                       </h3>
                                       <!-- <% if course.description.to_plain_text.length> 250 %>
                                         
                                          <% else %>
                                             <p>
                                                <%= course.description %>
                                             </p>
                                             <% end %> -->
                                    </div>
                                 </div>
                              </div>
                              <% end %>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>

      </div>
   </section>
   <!-- course area end -->


</main>

app/views/courses/show.html.erb
<main>

   <!-- event area start -->
   <section class="event__area pt-115 p-relative">
      <div class="page__title-shape">
         <img class="page-title-shape-5 d-none d-sm-block" src="assets/img/breadcrumb/page-title-shape-1.png" alt="">
         <img class="page-title-shape-6" src="assets/img/breadcrumb/page-title-shape-2.png" alt="">
         <img class="page-title-shape-7" src="assets/img/breadcrumb/page-title-shape-4.png" alt="">
         <img class="page-title-shape-8" src="assets/img/breadcrumb/page-title-shape-5.png" alt="">
      </div>
      <div class="container">
         <div class="row">
            <div class="col-xxl-8">
               <div class="event__wrapper">
                  <div class="page__title-content mb-25">
                     <div class="breadcrumb__list breadcrumb__list-2 mb-10">
                        <span>
                           <%= link_to "Home" , root_path%>
                        </span>
                        <span class="dvdr"><i class="fas fa-angle-right"></i></span>
                        <span>Courses</span>
                     </div>
                     <span class="breadcrumb__title-pre">
                        <%= @course.course_category.name%>
                     </span>
                     <h5 class="breadcrumb__title-2">
                        <%= @course.title%>
                     </h5>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- event area end -->

   <!-- event details area start -->
   <section class="event__area pb-110">
      <div class="container">
         <div class="row">
            <div class="col-xxl-8 col-xl-8 col-lg-8">
               <div class="event_wrapper">
                  <div class="event__thumb mb-35 w-img">
                     <% if @course.image.attached? %>
                        <%= image_tag @course.image %>
                     <% end %>
                  </div>
                  <div class="event__details mb-35">
                     <h3>Description</h3>
                     <p>
                        <%= @course.description %>
                     </p>
                  </div>

               </div>
            </div>
            <div class="col-xxl-4 col-xl-4 col-lg-4">
               <div class="event__sidebar pl-70">
                  <div class="event__sidebar-widget white-bg mb-20">
                     <div class="event__sidebar-shape">
                        <img class="event-sidebar-img-2" src="assets/img/events/event-shape-2.png" alt="">
                        <img class="event-sidebar-img-3" src="assets/img/events/event-shape-3.png" alt="">
                     </div>
                     <div class="event__info">
                        <div class="event__info-meta mb-25 d-flex align-items-center justify-content-between">
                           <div class="event__info-price">
                              <h5>RS<%= @course.price %>.<span>00</span> </h5>
                           </div>
                        </div>
                        <!-- <div class="event__info-content mb-35">
                           <ul>
                              <li class="d-flex align-items-center">
                                 <div class="event__info-icon">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                                       xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16"
                                       style="enable-background:new 0 0 16 16;" xml:space="preserve">
                                       <path class="st0"
                                          d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z" />
                                       <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 " />
                                    </svg>
                                 </div>
                                 
                              </li>
                              <li class="d-flex align-items-center">
                                 <div class="event__info-icon">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                                       xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16"
                                       style="enable-background:new 0 0 16 16;" xml:space="preserve">
                                       <path class="st0"
                                          d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z" />
                                       <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 " />
                                    </svg>
                                 </div>
                              </li>
                              <li class="d-flex align-items-center">
                                 <div class="event__info-icon">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                                       xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16"
                                       style="enable-background:new 0 0 16 16;" xml:space="preserve">
                                       <path class="st0"
                                          d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z" />
                                       <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 " />
                                    </svg>
                                 </div>
                              </li>
                           </ul>
                        </div> -->
                        <% if request.fullpath.include?('mycourse') %>
                        <% else %>
                        <div class="event__join-btn">
                        <% if current_user && !current_user.enrolled_in?(@course) %>
                           <%= link_to "Enroll" , new_course_enrollment_path(@course), class: 'tp-btn text-center w-100' %>
                        <% end %>
                        </div>

                        <% end %>
                     </div>
                  </div>

               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- event details area end -->


</main>